/* Generated by scripts/compile-seedance-25-skill.mjs. Do not edit manually. */
export type Seedance25VideoPromptRoute = "basic-multimodal" | "timestamp-30s" | "long-video" | "video-extension" | "video-edit" | "clay-renderer" | "seamless-transition" | "multi-grid-storyboard";

export type Seedance25VideoPromptReferenceInput = {
    prompt?: string;
    durationSeconds?: number;
};

export const SEEDANCE_25_DIRECTOR_SKILL = {
    id: "seedance-25-director",
    name: "Seedance 2.5 导演",
    description: "为 Seedance 2.5 提供供应商能力适配、素材职责和时间状态检查，不覆盖短剧公开视频导演契约。",
    plannerSummary: "需要多模态参考、续写、编辑或供应商时间轴适配时，使用 Seedance 2.5 适配规则。",
    sourceUrl: "https://github.com/liyue-aigc/seedance-2-5-video-director/tree/ad0e68ba6ce24fb9ae9c67c9276061cef37663f1",
    sourceRepository: "liyue-aigc/seedance-2-5-video-director",
    sourcePath: "SKILL.md",
    sourceVersion: "ad0e68ba6ce24fb9ae9c67c9276061cef37663f1",
    sourceCommit: "ad0e68ba6ce24fb9ae9c67c9276061cef37663f1",
    sourceContentHash: "ac981db5272df3f4dd2309a33328a9f8abad2fb195fd7c25580d31ba86b25230",
    license: "MIT",
    enabled: true,
    workspaces: ["video", "drama"],
    action: "generate",
    requiresReference: false,
    defaultConfig: {},
    keywords: ["Seedance 2.5", "多模态参考", "首尾帧", "视频续写", "视频编辑", "时间轴"],
    instructions:
        "# Seedance 2.5 供应商适配器\n\n## 使用边界\n\n本 Skill 只负责已验证的 Seedance 2.5 能力、模式、时长、画幅、清晰度和参考素材限制的适配，不调用供应商接口、不消耗积分，也不创建第二套短剧导演规则。用户事实、项目资产、已验收尾帧和服务端供应商协议优先于本文件。\n\n短剧制作包和 /api/drama/analyze 的公开视频 Prompt 必须服从 canonical drama-video-director Skill 的“小墨 6.3 简镜头卡”契约。本适配器不得要求公开 Prompt 使用旧版十二字段、八段标题，或逐段复制“起点 / 动作与触发 / 可见衔接 / 终点”。这些字段如需供应商执行，只能保留在内部 framePlan、表演、连续性和质量门禁字段中。\n\n## 模式路由\n\n每次请求只选择一个实际需要的供应商模式：\n\n- basic-multimodal：普通短视频。\n- timestamp-30s：用户或项目明确要求精确30秒时间轴。\n- long-video：用户明确要求长叙事。\n- video-extension：从已验收源视频继续新增区间。\n- video-edit：修改指定对象或时间区间。\n- clay-renderer、seamless-transition、multi-grid-storyboard：仅在用户明确提出且供应商能力已验证时使用。\n\n模式选择不决定逻辑片段数量、镜头数量或硬切次数。每个逻辑片段的时长和内部镜头密度来自当前项目配置与剧情事实；30秒、8帧或7—10次硬切不是所有请求的默认规则。\n\n## 供应商适配规则\n\n- 先按画幅设计构图：9:16优先单人、双人过肩、前中后景或上下纵深；16:9允许横向关系、长桌群像和空间展开。不得把横屏站位直接裁切成竖屏。\n- 参考素材按稳定 alias、role、purpose 和顺序传递；不新增、删除、重排或猜测参考图，不把参考图编号写成供应商执行数据。\n- 首帧和尾帧只按用户显式选择或项目已验收连续性状态提交；下一镜只使用上一镜已验收实际尾帧，不复制同组首镜起始状态。\n- 多人必须保留左右/前后、视线、支撑面、接触关系和空间锚点；画面过载时拆分信息，不缩小主体或使用虚化掩盖遮挡。\n- 所有公开卡片的时间范围、景别、焦段、机位、主运镜、场景、画面内容、光影、色调、台词、人声和音效由 Agent 直接生成；应用服务端只校验、拒绝和保存，不拼接或改写。\n- 直接对白使用“说话人说：‘实际台词’”；按自然语速分配对白游标，不能用异常加速塞入短时间段。\n\n## 内部质量协作\n\n本适配器与 canonical 导演 Skill 共用一份 authoring draft。内部 framePlan.frames[] 必须连续覆盖当前逻辑片段，保留真实时间边界、动作差异、对白时间、连续性、静态画面状态和硬切事件。每次切换必须带来新的角色反应、关系、动作、道具、空间或结果信息；只有用户或项目明确的密集剪辑策略才执行相应硬门禁。\n\n服务端质量门禁负责检查画幅构图、主体清晰度、遮挡、对白容量、相邻镜头重复、硬切信息差异、角色服装连续性和参考 alias 一致性。失败时返回具体修订项，不展示或提交半成品；每次返修只改变一个已定位变量，并保留已验收状态。\n\n## 参考资料\n\n真人表演、多人调度、镜头复刻或失败诊断需要时，读取本目录 references/ 下对应资料；参考资料只补充当前任务，不覆盖用户明确的素材、时长、比例、资产或公开 Prompt 契约。",
} as const;

const ROUTE_REFERENCES: Record<Seedance25VideoPromptRoute, string> = {
    "basic-multimodal":
        "模式：普通视频。\n适用于 15 或 20 秒普通视频。使用阶段节拍与可见结束状态，不机械逐秒拆分。先绑定每份参考素材的唯一职责，再写起始状态、一个主要动作链、一个有动机的主运镜、声音意图和可验证结束画面；多个事件只能在动作因果和表演时长允许时连续出现。",
    "timestamp-30s":
        "模式：30 秒精确时间轴。\n适用于用户或项目明确要求精确时间控制的镜头。内部时间段从起始到结束连续覆盖、不重叠、不留空；真实对白、停顿、反应和动作必须有足够的表演时间，禁止逐秒堆叠镜头或把多个关键事件挤在同一秒。短剧公开 videoPrompt 仍使用小墨 6.3 简镜头卡，内部起点、动作、衔接和终点只保存在 framePlan 等结构化字段中。",
    "long-video": "模式：长视频。\n适用于 30 秒以上的长叙事。按幕和序列组织，不罗列大量微镜头。每个序列写入口状态、主要事件、可见出口状态和与下一序列的连续性锁；身份、服装、空间方向、光向、声音母题和道具归属贯穿所有序列。",
    "video-extension":
        "模式：视频续写。\n适用于续写、延长、接着拍或扩展已有视频。必须明确新增片段放在源视频之前还是之后、添加时长和衔接边界。前置续写以源视频首帧为新增区间终点，后置续写以源视频尾帧为新增区间起点；只描述新增画面，保留原片内容、摄影机、光线、声音和空间关系，禁止无原因重置人物、道具或场景。",
    "video-edit":
        "模式：视频编辑。\n适用于智能编辑、局部替换、移除或删除。明确编辑位置或时间、目标对象、add/remove/replace/change 操作和 preserve 列表。未被点名的身份、服装、构图、动作、声音、字幕、背景和镜头运动保持不变；不要把局部编辑扩展成整段重生成。",
    "clay-renderer":
        "模式：白模控制。\n适用于粗白模或细白模控制。粗白模只继承走位、镜头、节奏、空间和动作关系；细白模可以继承构图和材质变化。最终画面必须移除轨迹线、坐标轴、相机锥体、灰模材质和辅助标记，并为每个主体补足最终身份、服装、环境、材质和光线。",
    "seamless-transition": "模式：无缝转场。\n适用于两段视频之间的无缝转场。两段源视频保持不变，只生成中间桥接段。明确连接物的形状、位置、比例、方向、速度、运动趋势、摄影机连续性和视觉变形；转场终点自然落到第二段的入口状态。",
    "multi-grid-storyboard": "模式：多宫格分镜。\n适用于多宫格分镜动画。每个格子是有序的完整镜头，不把分镜编号、边框、箭头或说明渲染进最终视频。按面板顺序锁定镜头的主体、场景、动作、机位和连续关系；只有需要独立补拍时才拆成首尾帧镜头对。",
};
const CONDITIONAL_REFERENCES = {
    realistic:
        "# 真人表演与对白\n\n附加参考：真人表演与对白。\n\n只在真人、角色对白、情感冲突、访谈、体育或综艺镜头中加载。\n\n- 先确定角色在本镜的目标、阻力和策略，再描述可观察行为；不要把“愤怒、害怕、感动”等情绪词当作完整表演指令。\n- 对白写清说话人、目标语言、短句、语气、停顿和重音；听者必须在接收到信息后才出现反应。\n- 情绪必须落到眉眼、嘴角、下颌、视线、呼吸、手部、重心、人与人距离或道具操作；每段至少保留一个可检查的变化。\n- 动作按准备、受力或接触、结果、恢复的因果顺序描述。人物必须有可见支撑面、合理接触点和真实可达的动作路径。\n- 只有需要表演变化时才增加镜头或时间段；不要用密集切镜掩盖缺少动机的表情变化。",
    multiCharacter:
        "# 多人物空间调度\n\n附加参考：多人物空间调度。\n\n只在两人及以上、对话、餐桌、车内、会议或群像任务中加载。\n\n- 用同一场景前进方向或镜头轴线描述人物左右、前后、朝向、视线和距离；不能在不同段落切换参照系。\n- 为每位出镜人物写明站立/坐姿支撑面、手部接触对象、道具归属、发言顺序和可见反应。\n- 封闭空间优先使用已有座位、长凳、床沿、桌面、通道、门窗和隔断；中央通道保持通行，未声明人物不入画。\n- 镜头反打、移动和转场保持屏幕方向、视线关系和 180 度轴线，除非 Prompt 明确设计了可观察的越轴动作。\n- 多人动作先减少并发事件，再让一个主体动作触发其他人的次级反应，避免同时出现无法辨认的手、道具和肢体归属。",
    example:
        "# 示例结构迁移\n\n附加参考：示例结构迁移。\n\n只在用户明确要求参考、模仿或复刻某个示例的结构时加载。\n\n- 先识别允许继承的维度：信息层级、时间粒度、镜头语法、节奏、动作因果、转场或声音组织。\n- 示例默认不转移人物身份、品牌、背景、台词、文字、水印、音乐、颜色或剧情；只有用户明确指定的维度才可继承。\n- 用当前用户的素材、角色、场景和时长重新构建 Prompt，不把示例描述直接拼接到新任务。\n- 复刻视频动作或镜头时，分别说明借用动作机制、摄影机节奏或构图中的哪一项，并写明不继承内容。",
    failure:
        "# 失败诊断\n\n附加参考：失败诊断。\n\n先按第一个失败层定位，不要一次重写全部提示词：\n\n1. 身份漂移：收紧唯一身份来源、服装、体型和道具归属。\n2. 参考串绑：拆分素材职责和作用范围，补充禁止继承项。\n3. 构图错误：固定景别、机位、屏幕方向和主体位置。\n4. 动作错误：补齐准备、接触/受力、结果和恢复的因果顺序。\n5. 物理错误：补足支撑面、接触点、距离、遮挡和空间通道。\n6. 时间错误：合并过密事件，使每段终点成为下一段起点。\n7. 音频错误：明确对白、环境声、音乐、静音和字幕之间的优先级。\n8. 连续性错误：只使用当前已验收的边界状态，不引用旧任务或未确认素材。\n\n诊断时先保留已经通过验收的身份、服装、资产、空间轴线、光向和声音；然后只改失败层的一项变量。示例结构、参考视频和角色素材出现冲突时，优先修正职责和作用范围，而不是追加更多泛化否定词。\n\n每次返修只改变一个已定位变量；保留通过验收的参考图、角色状态、空间轴线和声音规则。",
};
const REALISTIC_DIRECTION_RE = /真人|人物|角色|对话|台词|口型|情感|情绪|表演|情侣|访谈|综艺|体育|运动员/iu;
const MULTI_CHARACTER_RE = /多人|两人|双人|三人|四人|群像|对手|彼此|对话|会议|餐桌|车内/iu;
const EXAMPLE_STRUCTURE_RE = /参考(?:结构|示例|镜头)|参考\s*@?(?:图片|视频|音频)|模仿|复刻|参照/iu;
const FAILURE_DIAGNOSIS_RE = /失败|翻车|漂移|变形|模糊|错位|不一致|不符合|重试|修复/iu;

function conditionalReferences(prompt: string) {
    return [
        REALISTIC_DIRECTION_RE.test(prompt) ? CONDITIONAL_REFERENCES.realistic : "",
        MULTI_CHARACTER_RE.test(prompt) ? CONDITIONAL_REFERENCES.multiCharacter : "",
        EXAMPLE_STRUCTURE_RE.test(prompt) ? CONDITIONAL_REFERENCES.example : "",
        FAILURE_DIAGNOSIS_RE.test(prompt) ? CONDITIONAL_REFERENCES.failure : "",
    ].filter(Boolean);
}

export function resolveSeedance25VideoPromptRoute(input: Seedance25VideoPromptReferenceInput): Seedance25VideoPromptRoute {
    const prompt = input.prompt || "";
    if (/(?:智能|高级|局部)?编辑|替换|移除|删除|保留原片|change\s*\/\s*preserve/iu.test(prompt)) return "video-edit";
    if (/续写|延长|接着拍|接续|扩展|prepend|append/iu.test(prompt)) return "video-extension";
    if (/白模|clay(?:\s*renderer)?|blockout/iu.test(prompt)) return "clay-renderer";
    if (/无缝转场|两段视频|桥接(?:片段)?|seamless\s*transition/iu.test(prompt)) return "seamless-transition";
    if (/多宫格|分镜板|故事板|storyboard\s*grid/iu.test(prompt)) return "multi-grid-storyboard";
    if (/长视频|超长|long\s*video/iu.test(prompt) || (input.durationSeconds || 0) > 30) return "long-video";
    return input.durationSeconds === 30 ? "timestamp-30s" : "basic-multimodal";
}

export function resolveSeedance25VideoPromptReferences(input: Seedance25VideoPromptReferenceInput) {
    const route = resolveSeedance25VideoPromptRoute(input);
    return { route, instructions: [ROUTE_REFERENCES[route], ...conditionalReferences(input.prompt || "")].filter(Boolean).join("\n\n") };
}

export function inferSeedance25VideoDuration(prompt: string) {
    const values = Array.from(prompt.matchAll(/(?:^|[^\d])(\d{1,3})\s*(?:秒|s)(?!\w)/giu), (match) => Number(match[1])).filter((value) => Number.isFinite(value) && value > 0);
    return values.length ? values.at(-1) : undefined;
}

export function resolveSeedance25DirectorInstructions(input: Seedance25VideoPromptReferenceInput) {
    const reference = resolveSeedance25VideoPromptReferences(input);
    return { route: reference.route, instructions: SEEDANCE_25_DIRECTOR_SKILL.instructions + "\n\n" + reference.instructions };
}
