/* Generated by scripts/compile-drama-production-package-template.mjs. Do not edit manually. */
export const COMPILED_DRAMA_PACKAGE_CONTRACT = {
  id: "vozeb-drama-production-package-v1",
  version: "1.0.0",
  contentHash:
    "e3445b544ddf473f49eb3f7c488e10742436cb68ff7ce97d06cce3ef4097f312",
} as const;
export const COMPILED_DRAMA_PACKAGE_SPEC_HASH =
  "eb111df91977e74cdfb576bd4763a1dbe72f3ea747c7184f5a829c2982c99710" as const;
export const COMPILED_DRAMA_PACKAGE_TEMPLATE_SOURCE_HASH =
  "85602bfdd881d0d0e59e51f3c64bbb46d08f7dc4d2468989d82b868f9789d4a6" as const;
export const COMPILED_DRAMA_PACKAGE_RULES_HASH =
  "a0d00928e4ca2f0ffd6ec2572799f8be17aca381394e0fca7491dad3aa429de0" as const;
export const COMPILED_DRAMA_PACKAGE_AUTHORING_RULES =
  "- 制作包只能由 `executeDramaScriptRun` 组织；Agent 先返回 `mode=package` 的完整 authoring draft，服务端通过全部质量门禁后，才从规范对象确定性序列化 JSON/Markdown。\n- `package-template` 只规定 13 个一级章节、字段顺序和字段职责；`story-source` 只规定当前目标小说章节的剧情事实；`reference` 只规定素材职责。三类 authoring source 必须保留 alias、role、顺序和内容哈希。\n- 目标小说章节使用 `targetNarrativeChapter` 单独记录；它是剧情素材范围，不得与制作包一级章节编号混用。当前集必须提供完整文学剧本、场次、镜头和可执行结果，不能只返回摘要或镜头概述。\n- 镜头规范对象必须分别填写 `dramaticFunction`、`performancePlan`、`lightingPlan`、`continuity`、`entryState`、`exitState`、`videoPrompt` 和 `framePlan`；`framePlan.start.source`、`framePlan.end.required`、`framePlan.referenceManifest`、每个帧段的 `imagePrompt` 及其时间/动作/静态状态必须可校验。\n- 场景的 `backgroundNpcPolicy` 只描述无名背景群像；背景 NPC 不进入 characterCodes。required 场景的数量、前中后景分布和可见反应必须落到受影响的关键帧或视频时间段。\n- `videoPrompt` 和 `framePlan` 都由 Agent 直接生成；应用层不得从模板、旧包、历史提示词、动作字段或帧计划重建、补写、删改公开视频正文。未经声明的内部切镜、未绑定道具或未声明角色不得出现。\n- Agent authoring draft 的硬门禁代码来自版本化契约；至少包括文学剧本完整性、对白覆盖率、剧情事实覆盖率、动作密度/差异、情绪递进、NPC 反应变化、运镜动机、镜头事件、时间轴、素材绑定、连续性和 provenance。任一 blocker 都不得标记完成或写入正式制作包。" as const;
export const COMPILED_DRAMA_PACKAGE_SECTION_TITLES = [
  "项目总览",
  "原创第一章",
  "第一集文学剧本",
  "镜头执行表",
  "角色一致性资产",
  "场景一致性资产",
  "关键视频资产 Prompt",
  "全案板 Prompt",
  "台词与表演脚本",
  "声音设计",
  "分段视频 Prompt",
  "资产映射与执行顺序",
  "QC 报告",
] as const;
export const COMPILED_DRAMA_PACKAGE_GATE_CODES = [
  "LITERARY_SCRIPT_COMPLETENESS",
  "DIALOGUE_COVERAGE",
  "PLOT_FACT_COVERAGE",
  "ACTION_DENSITY",
  "ACTION_DIFFERENCE",
  "EMOTION_PROGRESSION",
  "NPC_REACTION_CHANGE",
  "CAMERA_MOTIVATION",
  "CAMERA_EVENT",
  "TIMELINE",
  "ASSET_BINDING",
  "CONTINUITY",
  "PROVENANCE",
] as const;
export const COMPILED_DRAMA_CODEX_WORK_ORDER_RULES =
  '外部 Codex 只能在项目 GPT 明确超时、任务已结束且用户主动确认后使用。\nCodex 只返回 mode=package 的 authoring draft；最终校验、序列化和导入仍由 executeDramaScriptRun 完成。\n提交时必须回传当前 workOrderId、契约/Skill 版本与内容哈希，以及模板/TXT/参考素材的 alias、role、顺序和内容哈希。\n- 触发条件：项目 GPT 已明确超时、运行已进入失败终态，且用户主动确认切换；不得自动并发调用外部模型。\n- 工作单输入：当前用户请求、模板全文（`role=package-template`）、TXT/小说全文（`role=story-source`）、参考素材职责、当前项目正式资产、当前集事实、目标小说章节、锁定生产方案，以及本契约和两个 Skill 的版本/内容哈希。\n- 草案输出：只能返回 `{ "mode": "package", "reply": "...", "markdown": "..." }`；Codex 不得直接导入、修改当前集或声明已生成正式制作包。\n- 回传校验：服务端重新核对 `runId`、`workOrderId`、用户身份、source alias/role/顺序/contentHash、契约哈希和两个 Skill 哈希；任一不一致直接拒绝。\n- 最终入口：草案回传后仍调用 `executeDramaScriptRun`，使用同一份门禁、规范对象和确定性序列化；最终 provenance 的 `provider` 才标记为 `codex-work-order`。\n\n本文件是制作包契约唯一规范源。`drama-production-package-v1-template.md` 只提供字段、章节和展示骨架；Skill、服务端门禁、Codex 工作单和运行时规则由本契约及编译产物提供，模板中的文字不能降低门禁。契约内容哈希由编译脚本生成并写入运行时与模板。' as const;
