import { normalizeDramaVoiceProfile } from "@/lib/drama-voice";
import { getDramaAssetMissingItems } from "@/lib/drama-asset-completion";
import type { DramaAssetCompletionKind as DramaAssetKind } from "@/lib/drama-asset-completion";
import { planDramaVoice } from "./drama-voice-planning";
import { refineDramaAssetWithModel } from "./drama-asset-refinement-service";
import { getDramaProjectForUser, updateDramaProjectForUser } from "./drama-project-service";
import { fetchInternalApi } from "./internal-origin";
import { approvedAssetReference } from "@/lib/drama-asset-baseline";
import { compileDramaAssetReferencePrompt, DRAMA_CHARACTER_TURNAROUND_SIZE } from "@/lib/drama-prompt-compiler";
import { createDramaVoiceCreationTask } from "./drama-voice-creation";

export async function completeDramaAsset(input: { userId: string; projectId: string; kind: DramaAssetKind; assetId: string; requestId: string; origin: string; cookie: string; config?: unknown; skipReference?: boolean; skipVoice?: boolean }) {
    let project = await getDramaProjectForUser(input.userId, input.projectId);
    const asset = project[input.kind].find((item) => item.id === input.assetId);
    if (!asset) throw new Error("项目资产不存在");
    const missing = getDramaAssetMissingItems(asset, input.kind);
    if (!missing.length) return { project, missingItems: [], planning: "not_needed", voice: "not_needed", reference: "not_needed" };
    const result: Record<string, unknown> = { missingItems: missing };

    if (missing.some((item) => item.task === "planning")) {
        if (input.kind === "clues") {
            const proposal = await refineDramaAssetWithModel({
                origin: input.origin,
                cookie: input.cookie,
                userId: input.userId,
                requestId: `${input.requestId}:planning`,
                project,
                kind: "props",
                asset,
                prompt: `只补全当前为空的字段：${missing
                    .filter((item) => item.task === "planning")
                    .map((item) => item.label)
                    .join("、")}；已填写字段不得改写。`,
            });
            project = await updateDramaProjectForUser(input.userId, project.id, {
                ...project,
                clues: project.clues.map((item) => (item.id === asset.id ? { ...item, description: proposal.updatedDescription || item.description, profile: proposal.updatedProfile } : item)),
            });
        } else {
            const proposal = await refineDramaAssetWithModel({
                origin: input.origin,
                cookie: input.cookie,
                userId: input.userId,
                requestId: `${input.requestId}:planning`,
                project,
                kind: input.kind,
                asset,
                prompt: `只补全当前为空的字段：${missing
                    .filter((item) => item.task === "planning")
                    .map((item) => item.label)
                    .join("、")}；已填写字段不得改写。`,
            });
            project = await updateDramaProjectForUser(input.userId, project.id, {
                ...project,
                [input.kind]: project[input.kind].map((item) => (item.id === asset.id ? { ...item, description: proposal.updatedDescription || item.description, profile: { ...item.profile, ...proposal.updatedProfile } } : item)),
            });
        }
        result.planning = "success";
    }

    const generateVoice = input.skipVoice !== true && input.config !== null && typeof input.config === "object" && (input.config as Record<string, unknown>).generateVoice === true;
    if (generateVoice && input.kind === "characters" && missing.some((item) => item.task === "voice")) {
        const current = project.characters.find((item) => item.id === asset.id)!;
        let voicePlan = normalizeDramaVoiceProfile(current.voiceProfile);
        try {
            const planned = await planDramaVoice({
                origin: input.origin,
                cookie: input.cookie,
                character: current,
                occupiedVoiceIds: project.characters
                    .filter((item) => item.id !== current.id)
                    .map((item) => item.voiceProfile?.voiceId || "")
                    .filter(Boolean),
                requestId: `${input.requestId}:voice`,
            });
            voicePlan = normalizeDramaVoiceProfile({ ...voicePlan, blueprint: planned.blueprint, instructions: planned.instructions, designPrompt: planned.designPrompt });
        } catch {
            // A deterministic role prompt is generated by the voice-creation service when planning is unavailable.
        }
        project = await updateDramaProjectForUser(input.userId, project.id, {
            ...project,
            characters: project.characters.map((item) => (item.id === current.id ? { ...item, voiceProfile: voicePlan } : item)),
        });
        const plannedCharacter = project.characters.find((item) => item.id === current.id)!;
        const created = await createDramaVoiceCreationTask({
            userId: input.userId,
            project,
            character: plannedCharacter,
            mode: "design",
            designPrompt: voicePlan.designPrompt,
            requestId: `${input.requestId}:voice`,
            origin: input.origin,
        });
        project = created.project;
        result.voice = created.task.status === "success" ? "success" : "running";
        result.voiceTaskId = created.task.id;
    }

    if (!input.skipReference && input.kind !== "clues" && missing.some((item) => item.task === "reference")) {
        const current = project[input.kind].find((item) => item.id === asset.id)!;
        const config = input.config && typeof input.config === "object" ? input.config : {};
        const response = await fetchInternalApi(`${input.origin}/api/image-tasks`, {
            method: "POST",
            headers: { "Content-Type": "application/json", cookie: input.cookie, "X-VOZEB-PRO-Client-Request-Id": `${input.requestId}:reference` },
            body: JSON.stringify({
                config: input.kind === "characters" ? { ...config, count: "1", size: DRAMA_CHARACTER_TURNAROUND_SIZE } : config,
                prompt: compileDramaAssetReferencePrompt(project, current, input.kind === "characters" ? "角色" : input.kind === "scenes" ? "场景" : "道具"),
                references: [],
                source: "drama",
                title: `${project.title} · ${current.name}智能补全`,
                context: { surface: "drama", projectId: project.id, clientRequestId: `${input.requestId}:reference` },
            }),
        });
        const payload = (await response.json().catch(() => ({}))) as { task?: { id?: string }; error?: string };
        if (!response.ok || !payload.task?.id) throw new Error(payload.error || "基准图任务创建失败");
        result.reference = "running";
        result.referenceTaskId = payload.task.id;
    }
    return { project, ...result };
}
