import type { DramaProductionPackageContract } from "@/lib/drama-project-contract";
import {
    COMPILED_DRAMA_CODEX_WORK_ORDER_RULES,
    COMPILED_DRAMA_PACKAGE_CONTRACT,
    COMPILED_DRAMA_PACKAGE_AUTHORING_RULES,
    COMPILED_DRAMA_PACKAGE_GATE_CODES,
    COMPILED_DRAMA_PACKAGE_RULES_HASH,
    COMPILED_DRAMA_PACKAGE_SECTION_TITLES,
    COMPILED_DRAMA_PACKAGE_SPEC_HASH,
    COMPILED_DRAMA_PACKAGE_TEMPLATE_SOURCE_HASH,
} from "./drama-production-package-contract.generated";

export const DRAMA_PACKAGE_CONTRACT_ID = COMPILED_DRAMA_PACKAGE_CONTRACT.id;
export const DRAMA_PACKAGE_CONTRACT_VERSION = COMPILED_DRAMA_PACKAGE_CONTRACT.version;

export const DRAMA_PACKAGE_SECTIONS = COMPILED_DRAMA_PACKAGE_SECTION_TITLES;
export const DRAMA_PACKAGE_GATE_CODES = COMPILED_DRAMA_PACKAGE_GATE_CODES;

export const DRAMA_PACKAGE_CONTRACT_CONTENT_HASH = COMPILED_DRAMA_PACKAGE_CONTRACT.contentHash;
export const DRAMA_PACKAGE_AUTHORING_RULES = COMPILED_DRAMA_PACKAGE_AUTHORING_RULES;

export const DRAMA_PACKAGE_CONTRACT: DramaProductionPackageContract = {
    id: DRAMA_PACKAGE_CONTRACT_ID,
    version: DRAMA_PACKAGE_CONTRACT_VERSION,
    contentHash: DRAMA_PACKAGE_CONTRACT_CONTENT_HASH,
};

export const DRAMA_PACKAGE_COMPILE_MANIFEST = {
    contract: DRAMA_PACKAGE_CONTRACT,
    packageSpecHash: COMPILED_DRAMA_PACKAGE_SPEC_HASH,
    templateSourceHash: COMPILED_DRAMA_PACKAGE_TEMPLATE_SOURCE_HASH,
    packageRulesHash: COMPILED_DRAMA_PACKAGE_RULES_HASH,
    sectionTitles: [...DRAMA_PACKAGE_SECTIONS],
    gateCodes: [...DRAMA_PACKAGE_GATE_CODES],
    authoringRules: DRAMA_PACKAGE_AUTHORING_RULES,
    codexWorkOrderRules: COMPILED_DRAMA_CODEX_WORK_ORDER_RULES,
} as const;

export function dramaPackageContractManifest() {
    return DRAMA_PACKAGE_COMPILE_MANIFEST;
}
